In [8]:
import numpy as np
import sympy
from sympy import MatrixSymbol, Identity, latex

from IPython.display import display, Latex

In [4]:
w = sympy.symarray("w", (8,), )
W = np.diag(w[1:-1])

In [5]:
D2 = np.diff(np.eye(8, dtype="i"), 2, axis=0)
print(D2)
print(D2.T @ D2)

[[ 1 -2  1  0  0  0  0  0]
 [ 0  1 -2  1  0  0  0  0]
 [ 0  0  1 -2  1  0  0  0]
 [ 0  0  0  1 -2  1  0  0]
 [ 0  0  0  0  1 -2  1  0]
 [ 0  0  0  0  0  1 -2  1]]
[[ 1 -2  1  0  0  0  0  0]
 [-2  5 -4  1  0  0  0  0]
 [ 1 -4  6 -4  1  0  0  0]
 [ 0  1 -4  6 -4  1  0  0]
 [ 0  0  1 -4  6 -4  1  0]
 [ 0  0  0  1 -4  6 -4  1]
 [ 0  0  0  0  1 -4  5 -2]
 [ 0  0  0  0  0  1 -2  1]]


In [6]:
DD2 = np.dot(np.dot(D2.T, W), D2)

In [9]:
s = r"$$\left(\begin{array}{llllllll}"
for i in range(8):
    for j in range(8):
        s += latex(DD2[i,j])
        if j < 7:
            s += r"&"
        else:
            s += r"\\"
s += r"\end{array}\right)$$"
# print(s)
display(Latex(s))

<IPython.core.display.Latex object>

In [10]:
D1 = np.diff(np.eye(8), 1, axis=0, )
print(D1)
print(D1.T @ D1)

[[-1.  1.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  1.]]
[[ 1. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  1.]]


In [11]:
w = sympy.symarray("w", (7,))
W = np.diag(w)
DD1 = np.dot(np.dot(D1.T, W), D1)

In [12]:
s = r"$$\left(\begin{array}{llllllll}"
for i in range(8):
    for j in range(8):
        s += latex(DD1[i,j])
        if j < 7:
            s += r"&"
        else:
            s += r"\\"
s += r"\end{array}\right)$$"
# print(s)
display(Latex(s))

<IPython.core.display.Latex object>

In [13]:
D3 = np.diff(np.eye(9), 3, axis=0, )
print(D3)
print(D3.T @ D3)

[[-1.  3. -3.  1.  0.  0.  0.  0.  0.]
 [ 0. -1.  3. -3.  1.  0.  0.  0.  0.]
 [ 0.  0. -1.  3. -3.  1.  0.  0.  0.]
 [ 0.  0.  0. -1.  3. -3.  1.  0.  0.]
 [ 0.  0.  0.  0. -1.  3. -3.  1.  0.]
 [ 0.  0.  0.  0.  0. -1.  3. -3.  1.]]
[[  1.  -3.   3.  -1.   0.   0.   0.   0.   0.]
 [ -3.  10. -12.   6.  -1.   0.   0.   0.   0.]
 [  3. -12.  19. -15.   6.  -1.   0.   0.   0.]
 [ -1.   6. -15.  20. -15.   6.  -1.   0.   0.]
 [  0.  -1.   6. -15.  20. -15.   6.  -1.   0.]
 [  0.   0.  -1.   6. -15.  20. -15.   6.  -1.]
 [  0.   0.   0.  -1.   6. -15.  19. -12.   3.]
 [  0.   0.   0.   0.  -1.   6. -12.  10.  -3.]
 [  0.   0.   0.   0.   0.  -1.   3.  -3.   1.]]
