In [1]:
import numpy as np

In [2]:
import mlgrad.pca.svd as svd

In [3]:
A = np.array([[1.,2.,3.],[4.,5.,6.]])

In [4]:
U, V, L = svd.find_uv_all(A, 2)
print(L)
print(U)
print(V)
print(A)

6
2
[9.508 0.773]
[[ 0.386  0.922]
 [ 0.922 -0.386]]
[[ 0.429  0.566  0.704]
 [-0.806 -0.112  0.581]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
U @ np.diag(L) @ V

array([[1., 2., 3.],
       [4., 5., 6.]])